//	@title			Gba File/JWT Auth Server
//	@version		1.0
//	@description	This server is designed to provide auth support and local file handling to my gbajs implementation

//	@contact.name	Nicholas VanCise
//	@contact.url	https://nicholas-vancise.dev
//	@contact.email	nvancisedev@gmail.com
//	@license.name	Copyright (c) 2025 Nicholas VanCise

package main

import (
	_ "auth-server/docs" // docs is generated by Swag CLI, you have to import it.
	"fmt"
	"log"
	"net/http"
	"os"

	uuid "github.com/satori/go.uuid"
	"github.com/spf13/afero"
	"gorm.io/gorm"
)

const (
	romPath  = "/local_roms/"
	savePath = "/local_saves/"
)

var (
	appFs         afero.Fs
	userdb        *gorm.DB
	accessSignKey []byte
)

func main() {
	log.Println("gbajs3 auth server started")
	var err error
	cfg := runtimeConfig{
		basePath:   "./data",
		certLoc:    "./certs/fullchain.pem",
		keyLoc:     "./certs/privkey.pem",
		clientHost: os.Getenv("CLIENT_HOST"),
	}
	logfile := newRollingLogger()
	gconf := newGormConfig(logfile)
	accessSignKey = uuid.NewV4().Bytes()
	log.SetOutput(logfile)

	userdb, err = newGbaJsDatabase(gconf)
	if err != nil {
		panic(fmt.Errorf("could not connect to gbajs3 db: %w", err))
	}

	appFs = afero.NewBasePathFs(afero.NewOsFs(), cfg.basePath)
	handler := newServerHandler(cfg.clientHost)

	log.Println("handling requests initiated")
	log.Fatal(http.ListenAndServeTLS(":443", cfg.certLoc, cfg.keyLoc, handler))
}
